name: Will Hou
year: 2025
bio: "Designer and engineer building products at the intersection of technology and creativity."
aboutImage: /images/about.svg
links:
  twitter: https://twitter.com/sirwillhou
  instagram: https://instagram.com/willhou
  email: mailto:hello@willhou.com
